In [54]:
############################
##### import libraries #####
############################
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

############################
##### Load Saved Files #####
############################
## Load trained Model
model = load_model('model.h5')

## Load Encoders
with open('label_encoder_gender.pkl', 'rb') as file:
    encoder_gender = pickle.load(file)

with open('one_hot_encoder.pkl', 'rb') as file:
    encoder_geo = pickle.load(file)

## Load Scaler
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [55]:
## Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [56]:
## Encode values
geo_encoded = encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns = encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

d:\Shivam Chaudhary\My Projects\1. ANN Classification Project - Churn Prediction\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [57]:
# Combine encoder values with input data
input_df = pd.DataFrame([input_data])
input_df['Gender'] = encoder_gender.transform(input_df['Gender'])
input_data = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)
input_data

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [60]:
# Scaling the input data
scaled_data = scaler.transform(input_data)
scaled_data

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [62]:
# Final Churn Prediction
prediction = model.predict(scaled_data)
prediction

1/1 [==============================] - 0s 75ms/step

array([[0.0530088]], dtype=float32)

In [64]:
pred_prob = prediction[0][0]
if pred_prob >= 0.5:
    print('Customer is likely to chrun')
else:
    print('Customer is not likely to churn')

Customer is not likely to churn